import type { ElementType } from 'react';
import {
  Activity,
  BarChart3,
  BookOpenText,
  Box,
  BrainCircuit,
  ClipboardCheck,
  Command,
  Gamepad2,
  Hourglass,
  LibraryBig,
  Lightbulb,
  Lock,
  Mail,
  MessageCircleQuestion,
  Network,
  Route,
  ScrollText,
  Sparkles,
  TicketPercent,
  Users,
  Waves,
  Zap,
} from 'lucide-react';

export type ServiceCategory = 'understand' | 'decide' | 'solve' | 'create' | 'plan' | 'personal';

export type TebyanService = {
  id: string;
  category: ServiceCategory;
  icon: ElementType;
  titleAr: string;
  titleEn: string;
  brandAr: string;
  brandEn: string;
  descriptionAr: string;
  descriptionEn: string;
  keywordsAr: string[];
  keywordsEn: string[];
  featured?: boolean;
};

export const SERVICE_CATEGORIES: Array<{
  id: ServiceCategory;
  titleAr: string;
  titleEn: string;
  descriptionAr: string;
  descriptionEn: string;
}> = [
  {
    id: 'understand',
    titleAr: 'أفهم موضوعاً',
    titleEn: 'Understand a topic',
    descriptionAr: 'شرح، تبسيط، ربط المفاهيم، واستكشاف المعرفة.',
    descriptionEn: 'Explain, simplify, connect concepts, and explore knowledge.',
  },
  {
    id: 'decide',
    titleAr: 'أحسم قراراً',
    titleEn: 'Make a decision',
    descriptionAr: 'قارن الخيارات واكشف المخاطر قبل أن تختار.',
    descriptionEn: 'Compare options and reveal risks before choosing.',
  },
  {
    id: 'solve',
    titleAr: 'أحل مشكلة أو موقفاً',
    titleEn: 'Solve a problem',
    descriptionAr: 'فكك الموقف، تدرّب عليه، واحصل على مسار عملي.',
    descriptionEn: 'Break down the situation, practise it, and get an action path.',
  },
  {
    id: 'create',
    titleAr: 'أبتكر وأطوّر فكرة',
    titleEn: 'Create and develop',
    descriptionAr: 'ولّد أفكاراً، امزج مجالات، وحوّل الخيال إلى تصور واضح.',
    descriptionEn: 'Generate ideas, combine fields, and turn imagination into a clear concept.',
  },
  {
    id: 'plan',
    titleAr: 'أخطط للمستقبل',
    titleEn: 'Plan the future',
    descriptionAr: 'حوّل الهدف أو المشروع إلى خطوات ومراحل قابلة للتنفيذ.',
    descriptionEn: 'Turn a goal or project into practical stages and steps.',
  },
  {
    id: 'personal',
    titleAr: 'مساحتي في تبيان',
    titleEn: 'My Tebyan space',
    descriptionAr: 'محفوظاتك، تقدمك، مكافآتك، ونتائجك السابقة.',
    descriptionEn: 'Your saved work, progress, rewards, and previous results.',
  },
];

export const TEBYAN_SERVICES: TebyanService[] = [
  {
    id: 'qawlfasl',
    category: 'understand',
    icon: MessageCircleQuestion,
    titleAr: 'أريد جواباً واضحاً ومحايداً',
    titleEn: 'I want a clear neutral answer',
    brandAr: 'قول فصل',
    brandEn: 'Qawl Fasl',
    descriptionAr: 'يعرض القضية بوضوح ويفصل بين الحجج والآراء بعيداً عن التشويش.',
    descriptionEn: 'Clarifies the issue and separates arguments from opinions without noise.',
    keywordsAr: ['جواب', 'رأي', 'نزاع', 'سؤال', 'حقيقة'],
    keywordsEn: ['answer', 'opinion', 'conflict', 'question', 'truth'],
    featured: true,
  },
  {
    id: 'knowledgecenter',
    category: 'understand',
    icon: Network,
    titleAr: 'أريد شرحاً منظماً لموضوع',
    titleEn: 'I want a structured explanation',
    brandAr: 'مركز المعرفة',
    brandEn: 'Knowledge Center',
    descriptionAr: 'يبحث في المفهوم ويرتب جذوره وروابطه وأبعاده في صورة مترابطة.',
    descriptionEn: 'Explores a concept and organizes its roots, links, and dimensions.',
    keywordsAr: ['شرح', 'بحث', 'مفهوم', 'معلومة', 'تعلم'],
    keywordsEn: ['explain', 'research', 'concept', 'information', 'learn'],
    featured: true,
  },
  {
    id: 'concepts',
    category: 'understand',
    icon: BookOpenText,
    titleAr: 'أريد تبسيط مفهوم معقد',
    titleEn: 'I want a complex concept simplified',
    brandAr: 'مفاهيم',
    brandEn: 'Concepts',
    descriptionAr: 'يحوّل المصطلحات والأفكار الصعبة إلى شرح قريب وسهل التذكر.',
    descriptionEn: 'Turns difficult terms and ideas into accessible memorable explanations.',
    keywordsAr: ['تبسيط', 'مصطلح', 'فهم', 'تعريف'],
    keywordsEn: ['simplify', 'term', 'understand', 'definition'],
  },
  {
    id: 'mindmap',
    category: 'understand',
    icon: BrainCircuit,
    titleAr: 'أريد خريطة مرتبة للأفكار',
    titleEn: 'I want an organized idea map',
    brandAr: 'الخريطة الذهنية',
    brandEn: 'Mind Map',
    descriptionAr: 'ينظم العناصر والفروع والعلاقات حتى ترى الصورة كاملة بسرعة.',
    descriptionEn: 'Organizes elements, branches, and relationships so the full picture is clear.',
    keywordsAr: ['خريطة', 'ترتيب', 'أفكار', 'هيكلة'],
    keywordsEn: ['map', 'organize', 'ideas', 'structure'],
  },
  {
    id: 'knowledgegraph',
    category: 'understand',
    icon: Waves,
    titleAr: 'أريد اكتشاف الروابط بين أفكاري',
    titleEn: 'I want to discover connections between ideas',
    brandAr: 'نسيج الأفكار',
    brandEn: 'Knowledge Graph',
    descriptionAr: 'يكشف العلاقات الخفية بين الموضوعات والأسئلة والنتائج المحفوظة.',
    descriptionEn: 'Reveals hidden relationships among topics, questions, and saved results.',
    keywordsAr: ['روابط', 'شبكة', 'أفكار', 'علاقات'],
    keywordsEn: ['links', 'network', 'ideas', 'relationships'],
  },
  {
    id: 'quizzes',
    category: 'understand',
    icon: ClipboardCheck,
    titleAr: 'أريد اختبار فهمي',
    titleEn: 'I want to test my understanding',
    brandAr: 'اختبر نفسك',
    brandEn: 'Knowledge Quiz',
    descriptionAr: 'أسئلة قصيرة تساعدك على التأكد مما فهمته وتحديد الفجوات.',
    descriptionEn: 'Short questions that check understanding and reveal gaps.',
    keywordsAr: ['اختبار', 'تقييم', 'فهم', 'أسئلة'],
    keywordsEn: ['quiz', 'test', 'understanding', 'questions'],
  },
  {
    id: 'decisionroom',
    category: 'decide',
    icon: Lock,
    titleAr: 'أنا محتار بين خيارات',
    titleEn: 'I am torn between options',
    brandAr: 'غرفة القرار',
    brandEn: 'Decision Room',
    descriptionAr: 'يفكك الحيرة ويقارن النتائج والمخاطر والقيم قبل الحسم.',
    descriptionEn: 'Breaks down uncertainty and compares outcomes, risks, and values.',
    keywordsAr: ['قرار', 'محتار', 'اختيار', 'مقارنة'],
    keywordsEn: ['decision', 'unsure', 'choice', 'compare'],
    featured: true,
  },
  {
    id: 'council',
    category: 'decide',
    icon: Users,
    titleAr: 'أريد سماع زوايا مختلفة',
    titleEn: 'I want several perspectives',
    brandAr: 'مجلس الآراء',
    brandEn: 'Council',
    descriptionAr: 'يعرض القضية من مدارس تفكير متعددة قبل أن تختار موقفك.',
    descriptionEn: 'Presents an issue through several schools of thought before you decide.',
    keywordsAr: ['آراء', 'وجهات نظر', 'مجلس', 'مقارنة'],
    keywordsEn: ['perspectives', 'views', 'council', 'compare'],
  },
  {
    id: 'oracle',
    category: 'decide',
    icon: Command,
    titleAr: 'أريد استشارة من تخصصات مختلفة',
    titleEn: 'I want multidisciplinary advice',
    brandAr: 'المستشار الكلي',
    brandEn: 'Omni Counselor',
    descriptionAr: 'يتيح لك النظر إلى السؤال بعقل متخصص مناسب لطبيعة المشكلة.',
    descriptionEn: 'Lets you view the question through the right specialist perspective.',
    keywordsAr: ['استشارة', 'خبير', 'تخصص', 'نصيحة'],
    keywordsEn: ['advice', 'expert', 'specialist', 'counsel'],
  },
  {
    id: 'simulation',
    category: 'solve',
    icon: Gamepad2,
    titleAr: 'أريد أن أتدرّب على موقف',
    titleEn: 'I want to practise a situation',
    brandAr: 'مختبر المحاكاة',
    brandEn: 'Simulation Lab',
    descriptionAr: 'تجربة تفاعلية للمحادثات والمواجهات قبل تطبيقها في الواقع.',
    descriptionEn: 'Interactive practice for conversations and confrontations before real life.',
    keywordsAr: ['تدريب', 'محاكاة', 'حوار', 'مواجهة'],
    keywordsEn: ['practice', 'simulation', 'conversation', 'confrontation'],
    featured: true,
  },
  {
    id: 'strategicarena',
    category: 'solve',
    icon: Activity,
    titleAr: 'أريد تحليل موقف معقد',
    titleEn: 'I want to analyse a complex situation',
    brandAr: 'الميدان الاستراتيجي',
    brandEn: 'Strategic Arena',
    descriptionAr: 'يفكك القوى والأطراف والاحتمالات ويقترح طريقة تعامل محسوبة.',
    descriptionEn: 'Maps forces, parties, and scenarios and suggests a measured response.',
    keywordsAr: ['تحليل', 'موقف', 'أزمة', 'استراتيجية'],
    keywordsEn: ['analyse', 'situation', 'crisis', 'strategy'],
  },
  {
    id: 'ripple',
    category: 'solve',
    icon: Waves,
    titleAr: 'أريد معرفة أثر قراري',
    titleEn: 'I want to see the impact of my decision',
    brandAr: 'أثر الفكرة',
    brandEn: 'Ripple Effect',
    descriptionAr: 'يتتبع ما قد يتغير بعد الفكرة أو القرار على المدى القريب والبعيد.',
    descriptionEn: 'Traces what may change after an idea or decision in the near and long term.',
    keywordsAr: ['أثر', 'نتيجة', 'تبعات', 'قرار'],
    keywordsEn: ['impact', 'outcome', 'consequence', 'decision'],
  },
  {
    id: 'creativelab',
    category: 'create',
    icon: Zap,
    titleAr: 'أريد أفكاراً جديدة وغير تقليدية',
    titleEn: 'I want fresh unconventional ideas',
    brandAr: 'المختبر الإبداعي',
    brandEn: 'Creative Lab',
    descriptionAr: 'يمزج الأفكار والمجالات ويولد حلولاً واتجاهات قابلة للتطوير.',
    descriptionEn: 'Combines ideas and fields to generate developable solutions and directions.',
    keywordsAr: ['فكرة', 'ابتكار', 'إبداع', 'حلول'],
    keywordsEn: ['idea', 'innovation', 'creative', 'solutions'],
    featured: true,
  },
  {
    id: 'lab',
    category: 'create',
    icon: Lightbulb,
    titleAr: 'أريد تجربة الفكرة وتطويرها',
    titleEn: 'I want to experiment with and develop an idea',
    brandAr: 'مختبر الأفكار',
    brandEn: 'Idea Lab',
    descriptionAr: 'مساحة اختبار وتعديل تساعدك على نقل الفكرة من مسودة إلى نموذج أقوى.',
    descriptionEn: 'An experiment space that moves an idea from draft to a stronger model.',
    keywordsAr: ['تجربة', 'تطوير', 'فكرة', 'نموذج'],
    keywordsEn: ['experiment', 'develop', 'idea', 'model'],
  },
  {
    id: 'truthmanuscript',
    category: 'create',
    icon: ScrollText,
    titleAr: 'أريد تحويل أفكاري إلى نص جميل',
    titleEn: 'I want to turn my thoughts into polished writing',
    brandAr: 'مخطوطة الحقيقة',
    brandEn: 'Truth Manuscript',
    descriptionAr: 'يصوغ التأملات والأفكار العميقة في نص فني متماسك.',
    descriptionEn: 'Shapes reflections and deep ideas into a coherent artistic text.',
    keywordsAr: ['كتابة', 'نص', 'تأمل', 'مخطوطة'],
    keywordsEn: ['writing', 'text', 'reflection', 'manuscript'],
  },
  {
    id: 'story',
    category: 'create',
    icon: Sparkles,
    titleAr: 'أريد شرح الفكرة بقصة',
    titleEn: 'I want the idea explained as a story',
    brandAr: 'صانع الحكاية',
    brandEn: 'Story Builder',
    descriptionAr: 'يحوّل المفهوم أو الرسالة إلى قصة قريبة من الناس وسهلة التذكر.',
    descriptionEn: 'Turns a concept or message into an accessible memorable story.',
    keywordsAr: ['قصة', 'حكاية', 'سرد', 'تبسيط'],
    keywordsEn: ['story', 'narrative', 'explain', 'simplify'],
  },
  {
    id: 'ar',
    category: 'create',
    icon: Box,
    titleAr: 'أريد رؤية المعرفة بصورة تفاعلية',
    titleEn: 'I want to see knowledge interactively',
    brandAr: 'واقع تبيان المعزز',
    brandEn: 'Tebyan AR',
    descriptionAr: 'يجسّد الأفكار والمفاهيم في تجربة بصرية تفاعلية ثلاثية الأبعاد.',
    descriptionEn: 'Embodies ideas and concepts in an interactive visual 3D experience.',
    keywordsAr: ['واقع معزز', 'ثلاثي الأبعاد', 'تفاعل', 'بصري'],
    keywordsEn: ['augmented reality', '3d', 'interactive', 'visual'],
  },
  {
    id: 'roadmap',
    category: 'plan',
    icon: Route,
    titleAr: 'أريد خطة واضحة خطوة بخطوة',
    titleEn: 'I want a clear step-by-step plan',
    brandAr: 'خارطة الطريق',
    brandEn: 'Roadmap',
    descriptionAr: 'يقسم الهدف إلى مراحل وأولويات وخطوات يمكن متابعتها.',
    descriptionEn: 'Breaks a goal into stages, priorities, and trackable actions.',
    keywordsAr: ['خطة', 'خطوات', 'هدف', 'تنفيذ'],
    keywordsEn: ['plan', 'steps', 'goal', 'execute'],
    featured: true,
  },
  {
    id: 'timemachine',
    category: 'plan',
    icon: Hourglass,
    titleAr: 'أريد استكشاف سيناريوهات المستقبل',
    titleEn: 'I want to explore future scenarios',
    brandAr: 'آلة الزمن',
    brandEn: 'Time Machine',
    descriptionAr: 'يقارن كيف قد تتغير النتائج باختلاف التوقيت والافتراضات.',
    descriptionEn: 'Compares how outcomes may change with timing and assumptions.',
    keywordsAr: ['مستقبل', 'سيناريو', 'توقع', 'زمن'],
    keywordsEn: ['future', 'scenario', 'forecast', 'time'],
  },
  {
    id: 'analytics',
    category: 'plan',
    icon: BarChart3,
    titleAr: 'أريد قياس التقدم والنتائج',
    titleEn: 'I want to measure progress and results',
    brandAr: 'لوحة التحليلات',
    brandEn: 'Analytics',
    descriptionAr: 'يعرض مؤشرات الاستخدام والتقدم لتعرف ما الذي يتحسن وما الذي يحتاج تركيزاً.',
    descriptionEn: 'Shows usage and progress indicators so you know what improves and what needs focus.',
    keywordsAr: ['تحليل', 'بيانات', 'تقدم', 'نتائج'],
    keywordsEn: ['analytics', 'data', 'progress', 'results'],
  },
  {
    id: 'mylibrary',
    category: 'personal',
    icon: LibraryBig,
    titleAr: 'أريد الرجوع إلى محفوظاتي',
    titleEn: 'I want to revisit my saved work',
    brandAr: 'مكتبتي',
    brandEn: 'My Library',
    descriptionAr: 'يجمع النتائج والأفكار والمخطوطات التي حفظتها للعودة إليها لاحقاً.',
    descriptionEn: 'Collects saved results, ideas, and manuscripts for later use.',
    keywordsAr: ['مكتبة', 'محفوظات', 'نتائج', 'حفظ'],
    keywordsEn: ['library', 'saved', 'results', 'bookmark'],
  },
  {
    id: 'contact',
    category: 'personal',
    icon: Mail,
    titleAr: 'أريد التواصل مع فريق تبيان',
    titleEn: 'I want to contact the Tebyan team',
    brandAr: 'تواصل معنا',
    brandEn: 'Contact Tebyan',
    descriptionAr: 'أرسل ملاحظة أو استفساراً أو اقتراحاً مباشرة إلى فريق المنصة.',
    descriptionEn: 'Send a note, question, or suggestion directly to the platform team.',
    keywordsAr: ['تواصل', 'دعم', 'رسالة', 'اقتراح'],
    keywordsEn: ['contact', 'support', 'message', 'suggestion'],
  },
  {
    id: 'loyalty',
    category: 'personal',
    icon: TicketPercent,
    titleAr: 'أريد معرفة نقاطي ومكافآتي',
    titleEn: 'I want to see my points and rewards',
    brandAr: 'الولاء والمكافآت',
    brandEn: 'Loyalty & Rewards',
    descriptionAr: 'يعرض مستوى العضوية والنقاط والكوبونات والامتيازات.',
    descriptionEn: 'Shows membership level, points, coupons, and benefits.',
    keywordsAr: ['نقاط', 'مكافآت', 'كوبونات', 'عضوية'],
    keywordsEn: ['points', 'rewards', 'coupons', 'membership'],
  },
];

export function getServiceLabel(service: TebyanService, language: 'ar' | 'en') {
  return language === 'ar' ? service.titleAr : service.titleEn;
}

export function getServiceBrand(service: TebyanService, language: 'ar' | 'en') {
  return language === 'ar' ? service.brandAr : service.brandEn;
}

export function getServiceDescription(service: TebyanService, language: 'ar' | 'en') {
  return language === 'ar' ? service.descriptionAr : service.descriptionEn;
}

export function getServiceTabs(language: 'ar' | 'en') {
  return TEBYAN_SERVICES.map((service) => ({
    id: service.id,
    label: getServiceLabel(service, language),
    brand: getServiceBrand(service, language),
    icon: service.icon,
    tooltip: getServiceDescription(service, language),
    category: service.category,
    hidden: false,
  }));
}
